global:
  scrape_interval:     20s
  evaluation_interval: 15h
  # scrape_timeout is set to the global default (10s).

# Alertmanager configuration
#alerting:
#  alertmanagers:
#  - static_configs:
#    - targets:
      # - alertmanager:9093

# Load rules once and periodically evaluate them according to the global 'evaluation_interval'.
rule_files:
  # - "first_rules.yml"
  # - "second_rules.yml"


scrape_configs:
  # The job name is added as a label `job=<job_name>` to any timeseries scraped from this config.
  - job_name: 'prometheus'
    static_configs:
    - targets: ['192.168.1.1:9090']
    relabel_configs:
    - source_labels: [__address__]
      regex: "([^:]+):\\d+"
      target_label: instance
    metric_relabel_configs:
    - source_labels: [__name__]
      regex: process_start_time_seconds|prometheus_remote_storage_.*|prometheus_target_sync_length_.*
      action: keep
    scrape_interval: 1m

#  - job_name: 'adguard'
#    static_configs:
#    - targets: ['localhost:9093']
#    scrape_interval: 3m

#    static_configs:
#    - targets: ['localhost:9090']

#  - job_name: 'node'
#    static_configs:
#    - targets: ['localhost:9100']

#    metric_relabel_configs:
#    - source_labels: [__name__]
#      regex: node_boot_time_seconds|node_load.*|node_memory_MemAvailable_bytes|node_memory_MemTotal_bytes|node_network_.*_bytes_total|node_wifi_station_(receive|signal|transmit)_.*
#      action: keep
#    - source_labels: [mac]
#      regex: ".+([[:xdigit:]]):([[:xdigit:]][[:xdigit:]]):([[:xdigit:]][[:xdigit:]])" 
#      target_label: mac_address
#      replacement: "$1$2$3"
#      action: replace
#    - source_labels: [mac_address]
#      regex: ".+([[:xdigit:]]):([[:xdigit:]][[:xdigit:]]):([[:xdigit:]][[:xdigit:]])" 
#      target_label: mac_address
#      replacement: "$1$2$3"
#      action: replace

  - job_name: 'node-lua'
    static_configs:
    - targets: ['192.168.1.1:9101']
    relabel_configs:
    - source_labels: [__address__]
      regex: "([^:]+):\\d+"
      target_label: instance
    metric_relabel_configs:
    - source_labels: [__name__]
      regex: node_boot_time_seconds|node_directory_size_.*|node_load.*|node_memory_MemAvailable_bytes|node_memory_MemTotal_bytes|node_network_.*_bytes_total|node_wifi_station_(receive|signal|transmit)_.*|node_uname_info
      action: keep
    - source_labels: [mac]
      regex: ".+([[:xdigit:]]):([[:xdigit:]][[:xdigit:]]):([[:xdigit:]][[:xdigit:]])" 
      target_label: mac
      replacement: "$1$2$3"

remote_write:
- url: https://prometheus-blocks-prod-us-central1.grafana.net/api/prom/push
  basic_auth:
    username: 67951
    password: eyJrIjoiNGFiYjBhZGFkZjc2NjIzZjI5Y2NlYTMyYzQ4Y2YxOTU2ZjkzOGU4YyIsIm4iOiJwcm9tZXRoZXVzIiwiaWQiOjQ3NjU2MH0=

