#!/bin/sh /etc/rc.common
USE_PROCD=1
START=90
STOP=05

start_service() {
    procd_open_instance
    procd_set_param command /opt/metrics/collectd_exporter-0.5.0.linux-armv7/collectd_exporter
    procd_append_param command --collectd.listen-address=":25826"
    procd_set_param respawn
    procd_set_param stdout 1
    procd_set_param stderr 1
    procd_set_param user nobody
    procd_close_instance
}
