#!/bin/sh /etc/rc.common
USE_PROCD=1
START=97
STOP=01

start_service() {
    procd_open_instance
    procd_set_param command /opt/metrics/node_exporter-1.1.2.linux-armv7/node_exporter
    procd_append_param command --collector.disable-defaults
    procd_append_param command --collector.loadavg
    procd_append_param command --collector.meminfo
    procd_append_param command --collector.netdev
    procd_append_param command --collector.stat
    procd_append_param command --collector.uname
    procd_append_param command --collector.wifi

    procd_set_param nice 5
    procd_set_param respawn
    procd_set_param stdout 1
    procd_set_param stderr 1
    procd_set_param user nobody
    procd_close_instance
}
