#!/bin/sh /etc/rc.common
USE_PROCD=1
# use same priority from prometheus-node-exporter
START=60
STOP=01


name=node_exporter
pidFile=/var/run/${name}.pid


start_service() {
    procd_open_instance
    procd_set_param command /opt/metrics/${name}/${name}
    procd_append_param command --collector.disable-defaults
#    procd_append_param command --collector.loadavg
#    procd_append_param command --collector.meminfo
#    procd_append_param command --collector.netdev
#    procd_append_param command --collector.stat
#    procd_append_param command --collector.uname
    procd_append_param command --collector.wifi
#    procd_append_param command --collector.textfile
#    procd_append_param command --collector.textfile.directory="/tmp/prometheus"
    procd_append_param command --web.listen-address="192.168.1.1:9100"

    procd_set_param nice 15
    procd_set_param pidfile $pidFile
    procd_set_param respawn
    procd_set_param stdout 1
    procd_set_param stderr 1
    procd_set_param user nobody
    procd_close_instance
}
