#!/bin/sh /etc/rc.common
USE_PROCD=1
START=98
STOP=01

promtailDir=/opt/metrics

start_service() {
    procd_open_instance
    procd_set_param command ${promtailDir}/promtail-linux-arm
    procd_append_param command -config.file="${promtailDir}/promtail.yaml"

    procd_set_param nice 5
    procd_set_param respawn
    procd_set_param stdout 1
    procd_set_param stderr 1
    procd_set_param user nobody
    procd_close_instance
}
