#!/bin/sh /etc/rc.common
USE_PROCD=1
START=99
STOP=01

name=prometheus
promDir=/opt/metrics/prometheus
dataDir=/var/log/${name}/data
pidFile=/var/run/${name}.pid

start_service() {

    [ -d "$dataDir" ] || mkdir -m 0755 -p "$dataDir"
    chown -R nobody.nogroup $dataDir

    procd_open_instance
    procd_set_param command ${promDir}/prometheus
    procd_append_param command --config.file="${promDir}/prometheus.yml"
    procd_append_param command --enable-feature="agent"
    procd_append_param command --storage.agent.path="${dataDir}"
#    procd_append_param command --storage.tsdb.path="${dataDir}"
#    procd_append_param command --storage.tsdb.retention.size="1MB"
#    procd_append_param command --storage.tsdb.retention.time="1h"
#    procd_append_param command --storage.tsdb.wal-segment-size="10MB"
#    procd_append_param command --web.listen-address="192.168.1.1:9090"

    procd_set_param nice 15
    procd_set_param pidfile $pidFile
    procd_set_param stdout 1
    procd_set_param stderr 1
    procd_set_param user nobody
    procd_set_param respawn
    procd_close_instance
}


reload_service() {
    kill -1 `eval cat  $pidFile`
}


restart() {
    trap '' TERM
    stop "$@"
    rm -rf $dataDir 
    trap - TERM
    start "$@"
}
